// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide
:projectid: springboot-mvc
:page-duration: 20 minutes
:page-releasedate: 2018-10-05
:page-description: Learn how to run a Spring Boot MVC application as a WAR file in Open Liberty instead of an embedded container.
:page-tags: ['Spring Boot', 'Maven']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Running a Spring Boot MVC application as a WAR file

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to run a Spring Boot Model-View-Controller (MVC) application as a WAR file in Open Liberty instead of an embedded container.

== What you'll learn
You will learn how to use Maven to run a sample Spring Boot Model-View-Controller (MVC) application as a WAR file in Open Liberty. The sample application that you will be working with is from Spring's https://spring.io/guides/gs/serving-web-content/[Serving Web Content with Spring MVC] guide. If you are not familiar with Spring Boot or Spring MVC, it will be helpful to to complete that guide before proceeding.

Three main steps are required to build the WAR file from the Spring Boot MVC application. First, you will modify the project POM, primarily to remove Tomcat and add the Liberty Maven Plugin. Next, you will configure the Open Liberty server through a `server.xml` file. Finally, you will modify the application to run from a traditional WAR deployment. After these steps are complete, you will package and deploy the application to Open Liberty. This guide will not cover running the Spring Boot MVC test cases in Open Liberty, and the starting project does not include test code or dependencies.

include::{common-includes}/gitclone.adoc[]

=== Running the application in embedded Tomcat
You might first want to run the initial Spring Boot application without modifications. Move to the `start` directory and run the sample application in embedded Tomcat. Java 8 or later is required.

----
cd start
mvn spring-boot:run
----

Notice that the console output will display that the application is running in Tomcat on port 8080. Now access the application at the following URL: http://localhost:8080/greeting?name=GreetingApplication

You'll see from the page output that the `name` request parameter from the URL was received and handled:

----
Hello, GreetingApplication!
----

You are now ready to build the application into a WAR file and run in Open Liberty instead of embedded Tomcat.

== Modifying the POM

You will modify the `pom.xml` file in several steps. For reference, the completed `pom.xml` is provided at the end of this section.

Navigate to the `start` directory to begin.

=== Changing the packaging type
Start by setting the application packaging type to liberty-assembly. No packaging type is specified in the starting project, so add `<packaging>liberty-assembly</packaging>` after `<version>1.0-SNAPSHOT</version>` in the POM.

=== Adding POM properties
Next, add the `<start-class>hello.Application</start-class>` property to the `properties` block, which should look this afterwards:

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=properties]
----

The `start-class` property references the fully qualified Spring Boot startup class; in this case `src/main/java/hello/Application.java`. This property indicates the main class to use for the runnable JAR.

=== Adding and modifying dependencies

In the project dependencies, the `spring-boot-starter-thymeleaf` artifact depends on the `spring-boot-starter-web` dependency. Because `spring-boot-starter-web` uses Tomcat as the default embedded server, you will need to exclude it in your configuration to run your application on Open Liberty. Modify the `spring-boot-starter-thymeleaf` dependency definition to look like this:

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=dependency-with-exclusion]
----

You can also remove the `spring-boot-devtools` dependency since you are running on Open Liberty.

=== Adding the Liberty Maven Plugin
Finally, replace the `spring-boot-maven-plugin` configuration with the `liberty-maven-plugin` configuration inside the `<build> <plugins>` block:

[source, xml, indent=0]
----
include::finish/pom.xml[tags=liberty-maven-plugin]
----

In this plugin, you specify an Open Liberty server called `MVCServer` which the application will be deployed to. You also set `<include>runnable</include>` to indicate that the application will be packaged into a runnable JAR, which is set to be called `MVCServerPackage.jar` in the `<packageFile>` parameter.

Further documentation of the plugin configuration is provided in the https://github.com/WASdev/ci.maven[ci.maven] repository.

=== Completed pom.xml

After updating your `pom.xml`, it should look as shown in the following example:

[source, xml, indent=0]
----
include::finish/pom.xml[tags=**;!copyright;]
----

== Configuring the server
Next, provide the configuration for the Open Liberty server. Create a `src/main/liberty/config/server.xml` server configuration file.

[source,xml,indent=0]
----
include::finish/src/main/liberty/config/server.xml[tags=**;]
----

In the server configuration, the application context root is mapped to the server root directory. The `servlet-3.1` feature is also needed for running the application. The `<applicationManager autoExpand="true" />` configuration automatically expands the WAR file and the `<webContainer deferServletLoad="false"/>` configuration automatically loads the Spring application endpont once the server is ready.

== Changing the application startup process
Traditionally, a Spring Boot application running on an embedded server such as Tomcat calls `SpringApplication.run(...)` in its main class. In this case, the main class is `hello.Application`. However, your class needs to extend `SpringBootServletInitializer` when being deployed to an Open Liberty server. Replace the original code in `src/main/java/hello/Application.java` with the following code:

[source, Java]
----
include::finish/src/main/java/hello/Application.java[tags=**;!copyright;]
----

Also recall that you previously set the `<start-class>` parameter in the POM properties above to `hello.Application`. This tells the server that your application starts its execution from this class.

This concludes the code changes; you are now ready to build and run your application in Open Liberty.

include::{common-includes}/mvnbuild.adoc[]

Now verify that your Spring Boot application is running in Open Liberty. Navigate to the following URL: http://localhost:9080/greeting?name=GreetingApplication. Notice that the port has changed to 9080, as this is the default port used by Open Liberty. You will see the same output on this page as in the starting application.

include::{common-includes}/mvncompile.adoc[]

== Great work! You're done!

You built a WAR file from a basic Spring Boot MVC application to run in Open Liberty.

include::{common-includes}/finish.adoc[]
