// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide
:projectid: springboot-mvc
:page-duration: 30 minutes
:page-releasedate: 2018-11-17
// INSTRUCTION: Provide a description for the guide index page.
:page-description: Learn how to migrate a Spring Boot MVC application to run in Open Liberty.
// INSTUCTION: Please provide relevant tags, try to avoid inventing new ones, tags where there is 1 guide for the tag isn't useful.
:page-tags: ['Spring Boot', 'Migration', 'Maven']
// INSTRUCTION: Specify the unique name of the guide that is used in the permalink.  For example below, it is rest-service
// INSTRUCTION: Specify the slug in the website. This must be unique.
:page-permalink: /guides/spring-boot-mvc-migration
// INSTRUCTION: You should have this to source the common page elements, clone git@github.com:OpenLiberty/guides-common.git
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
// INSTRUCTION: You can't have a new line between the attributes and the title.
// The details of what to fill in for this template are in the comments. So, read the source for this template to see the comments.
//
// Example title: Creating a RESTful web service
= Migrating a Spring Boot MVC Application to Open Liberty

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to migrate a Spring Boot Model-View-Controller (MVC) application to run in Open Liberty instead of an embedded container. 
// Write no more than two sentences, or about fifty words with meaningful information on what the user can accomplish with this guide.
// Do not start the introduction with "This guide...".

== What you'll learn
You will learn how to use Maven to migrate a sample Spring Boot Model-View-Controller (MVC) application to run in Open Liberty. The sample application that you will be migrating is from Spring's https://spring.io/guides/gs/serving-web-content/[Serving Web Content with Spring MVC] guide. If you are not familiar with Spring Boot or Spring MVC, it will be helpful to to complete that guide before proceeding. 

Three main steps are required to perform the migration. First, you will modify the project POM, primarily to remove Tomcat and add the Liberty Maven Plugin. Next, you will configure the Open Liberty server through a `server.xml` file. Finally, you will modify the application to run from a traditional WAR deployment. After the migration is complete, you will package and deploy the application to Open Liberty. This guide will not cover migration of test cases, and the starting project does not include test code or dependencies. 

// Add this getting started section to your guide if it is applicable. Use the following include to pull in the git clone instructions from the guides-common repo.
include::{common-includes}/gitclone.adoc[]

=== Running the application in embedded Tomcat
You might first want to run the initial Spring Boot application without modifications. Move to the `start` directory and run the sample application in embedded Tomcat. Java 8 or later is required. 

----
cd start
mvn spring-boot:run
----

Notice that the console output will display that the application is running in Tomcat on port 8080. Now access the application at the following URL: http://localhost:8080/greeting?name=GreetingApplication

You'll see from the page output that the `name` request parameter was received and handled:

----
Hello, GreetingApplication!
----

You are now ready to migrate the application to run in Open Liberty instead of embedded Tomcat. 

== Modifying the POM

Navigate to the `start` directory. You will modify the `pom.xml` file in several steps. 

----
include::finish/pom.xml
----

=== Changing the packaging type
Start by setting the application packaging type to liberty-assembly. No packaging type is specified in the starting project, so you'll need to add `<packaging>liberty-assembly</packaging>` near the top of the POM.

=== Adding POM properties
Next, add the `<start-class>hello.Application</start-class>` property. The `properties` block should look like this afterwards:

----
<properties>
    <java.version>1.8</java.version>
    <start-class>hello.Application</start-class>
</properties>
----

The `start-class` property references the fully qualified Spring Boot startup class; in this case `hello.Application`. This property indicates the main class to use for the runnable JAR.

=== Adding and modifying dependencies

The `spring-boot-starter-thymeleaf` artifact transitively depends on the `spring-boot-starter-web` dependency. Because `spring-boot-starter-web` uses Tomcat as the default embedded server, you will need to exclude it in your configuration to run your application in Open Liberty. Thus, add the following exclusion to the `spring-boot-starter-thymeleaf` dependency:

----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-thymeleaf</artifactId>
    <!-- Add this -->
    <exclusions>
        <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </exclusion>
    </exclusions>
</dependency>
----

You can also remove the `spring-boot-devtools` dependency. 

=== Adding the Liberty Maven Plugin
Finally, replace the `spring-boot-maven-plugin` configuration with the `liberty-maven-plugin` configuration as shown below.

----
<plugin>
	<groupId>net.wasdev.wlp.maven.plugins</groupId>
	<artifactId>liberty-maven-plugin</artifactId>
	<version>2.4.2</version>
	<extensions>true</extensions>
	<!-- Specify configuration, executions for liberty-maven-plugin -->
	<configuration>
		<serverName>MVCServer</serverName>
		<assemblyArtifact>
			<groupId>io.openliberty</groupId>
			<artifactId>openliberty-runtime</artifactId>
			<version>RELEASE</version>
			<type>zip</type>
		</assemblyArtifact>
		<configFile>src/main/liberty/config/server.xml</configFile>
		<assemblyInstallDirectory>${project.build.directory}/liberty</assemblyInstallDirectory>
		<packageFile>${project.build.directory}/MVCServerPackage.jar</packageFile>
		<features>
			<acceptLicense>true</acceptLicense>
		</features>
		<include>runnable</include>
		<installAppPackages>all</installAppPackages>
		<appsDirectory>apps</appsDirectory>
		<stripVersion>true</stripVersion>
		<looseApplication>true</looseApplication>
		<skipTestServer>true</skipTestServer>
	</configuration>
</plugin>
----


In this plugin, you specify an Open Liberty server called "MVCServer" which the application will be deployed to. You also set `<include>runnable</include>` to indicate that the application will be packaged into a runnable JAR, which is set to be called `MVCServerPackage.jar` in the `<packageFile>` parameter.

Further documentation of the plugin configuration is provided in the https://github.com/WASdev/ci.maven/tree/tools-integration[ci.maven] repository.

== Configuring the server
Next, provide the configuration for the Open Liberty server. Create a `src/test/resources/server.xml` server configuration file (this is the default location defined by the `configFile` configuration parameter in the `liberty-maven-plugin`):

----
<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">
	<application context-root="/"
		location="guide-spring-boot-mvc"></application>

	<!-- Enable features -->
	<featureManager>
		<feature>servlet-3.1</feature>
	</featureManager>

	<!-- To access this server from a remote client add a host attribute to 
		the following element, e.g. host="*" -->
	<httpEndpoint id="defaultHttpEndpoint" httpPort="9080"
		httpsPort="9443" />

	<!-- Automatically expand WAR files and EAR files -->
	<applicationManager autoExpand="true" />
    
    <!-- Automatically load the Spring application endpoint once the server 
		is ready. -->
	<webContainer deferServletLoad="false"/>

</server>
----

In the server configuration, the application context root is mapped to the server root directory. The `servlet-3.1` feature is also needed for running the application, as well as other items which are described in the XML comments. 

== Changing the application startup process
Traditionally, a Spring Boot application running on an embedded server such as Tomcat simply calls `SpringApplication.run(...)` in its main class (in this case `hello.Application`). However, your class needs to extend `SpringBootServletInitializer` instead when being deployed to an Open Liberty server. Replace the original class with the following code:

----
package hello;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

@SpringBootApplication
public class Application extends SpringBootServletInitializer {

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(Application.class);
	}
}
----

Also recall that you previously set the `<start-class>` parameter in the POM properties above to `hello.Application`. This tells the server that your application starts its execution from this class.

This concludes the code changes; you are now ready to build and run your application in Open Liberty.

// Use the following include to pull in the Maven build instructions from the guides-common repo.
include::{common-includes}/mvnbuild.adoc[]

Now verify that your Spring Boot application is running in Open Liberty. Navigate to the following URL (notice that the port has changed to 9080): http://localhost:9080/greeting?name=GreetingApplication

You will notice the same output as in the starting application.

// Use the following include to pull in the Liberty start/stop server instructions from the guides-common repo.
include::{common-includes}/mvncompile.adoc[]

== Great work! You're done!

You migrated a basic Spring Boot MVC application to run in Open Liberty.

// Briefly summarize what the user achieved in this guide (1-2 sentences).

// OPTIONAL: briefly state what the user could do next now that they've learned the technologies in this guide.

// Include the below from the guides-common repo to tell users how they can contribute to the guide
include::{common-includes}/finish.adoc[]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
